[workspace]
members = [
   "byods/ascent-byods-rels",
   "ascent",
   "ascent_base",
   "ascent_dd_runtime",
   "ascent_macro",
   "ascent_mir",
   "ascent_codegen_dd",
   "ascent_codegen_batch",
   "ascent_tests_dd",
]
exclude = ["ascent_tests", "ascent_tests_dd", "wasm-tests", "benches"]
resolver = "2"

[workspace.package]
version = "0.8.0"

[workspace.dependencies]
ascent = { path = "./ascent", default-features = false, version = "0.8.0" }
ascent_macro = { path = "./ascent_macro", version = "0.8.0" }
ascent_base = { path = "./ascent_base", version = "0.8.0" }
ascent_dd_runtime = { path = "./ascent_dd_runtime", version = "0.8.0" }
ascent_mir = { path = "./ascent_mir", version = "0.8.0" }
ascent_codegen_dd = { path = "./ascent_codegen_dd", version = "0.8.0" }
ascent_codegen_batch = { path = "./ascent_codegen_batch", version = "0.8.0" }
