[package]
name = "slog"
edition = "2024"
authors = ["Yihao Sun"]
version.workspace = true

[dependencies]
syn = { version = "2.0.57", features = ["derive", "full", "extra-traits", "visit-mut"] } 
quote = "1.0"
ascent_base = { workspace = true }
proc-macro2 = "1.0"
itertools = "0.12.0"
petgraph = "0.6.0"
derive-syn-parse = "0.2.0"
lazy_static = "1.4.0"
duplicate = { version = "1.0.0", default-features = false }
macro_magic = { version = "*", features = ["proc_support"] }
rand = "0.9.0"
ascent = { path = "../ascent"}
ascent-byods-rels = { path = "../byods/ascent-byods-rels" }
slog_eq_theory = { path = "../slog_eq_theory" }

[lib]
proc-macro = true

[dev-dependencies]
ascent = { path = "../ascent"}
slog_eq_theory = { path = "../slog_eq_theory" }

[features]
default = ["par"]
compact = []
par = ["ascent/par"]
