[package]
name = "slog_test"
edition = "2024"
version.workspace = true

[dependencies]
slog = { path = "../slog" }
slog_theory = { path = "../slog_theory" }
slog_utils = { path = "../slog_utils" }
ascent = { path = "../ascent" }
ascent-byods-rels = { path = "../byods/ascent-byods-rels" }
lazy_static = "1.4.0"
# eager2 = "1.1.4"
eager = "*"
egg = "0.10.0"
ordered-float = "5.1.0"
